### ISSUE TITLE
Bugs in v0.2.0 for MC 1.12

### ISSUE THREAD

**Issue by Tschipp** [DarkRoleplay/Dark-Roleplay-Medieval#8]
Hello
I enjoy your mod and it fits nicely into my modpack, while playing around I found some issues:

Minor:
- The correct past tense of "download" is "downloaded", not "downloadet". There might be more typos, you might want to get it checked out by an english native.
- Most blocks with the name "acacia" have incorrect localisation. Check your lang file.
- Wheat and barley dough have incorrect localisation.

Major:
- The crate's gui has a missing texture.
- The game crashes when trying to preview Rustic's Iron Lattice (pressing shift). The problem might be on Rustic's end but I'll leave it here too. https://pastebin.com/BtBRDCwj

**Comment by JTK222** [comment]
Thank you for the reports. Might I ask what's your Minecraft name?
(Working on a reward system for people that report bugs)

The downloadet -> downlaoded thing will be fixed with the next version.
I haven o Idea why the translation for blocks with acacia is broken... might have been an export issue cause it works in my dev env. Will do my best to fix it. (Same for the doughs)

I am always forgetting to fix the Crate gui, thank you ^^
But I am not sure if it's worth it, working on a new Container system that generates it textures as needed.
I will try to fix the preview crash but I cannot promise anything because they are using a custom renderer thingy and have insuffizient error handling.

I might however try to find a solution for it, as this might happen with a lot more mods too.

**Comment by JTK222** [comment]
Everything except the crash is fixed. (The crash is from the core mod not medieval mod).

**Comment by Tschipp** [comment]
My Minecraft name is Tschipp. 
And about the translation: in the dev environment it will ignore big and lowercase and treat it as one, but not when you export it. ;)

**Comment by JTK222** [comment]
Knew that with upper and lowercase. And I found the issue xD I had the correct file in the wrong directory, that's why I couldn't find any errors in the lang file :P Now it's fixed and released ^^
